language: python
arch:
  - amd64
  - ppc64le
python:
  - "3.6"
  - "3.7"

install:
  - pip install codecov tox

script:
  - tox -e py3,lint

after_success:
  - codecov --env TRAVIS_PYTHON_VERSION

branches:
  only:
    - master
